[package]
name = "private-inference"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1.0.228"
serde_json = "1.0.149"
tfhe = { version = "*", features = ["boolean", "shortint", "integer"] }

[[bin]]
name = "private-inference"
path = "main.rs"
