[package]
name = "private-inference"
version = "0.1.0"
edition = "2024"

[dependencies]
tfhe = { version = "*", features = ["boolean", "shortint", "integer"] }

[[bin]]
name = "private-inference"
path = "main.rs"
